{{- if .Values.clientExtensionConfig.setupMainDomainOnCoreDNS -}}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-pre-delete-configmap
    namespace: kube-system
data:
    append-nodehost.sh: |-
{{ .Files.Get "scripts/remove-nodehost.sh" | indent 8 }}
---
apiVersion: batch/v1
kind: Job
metadata:
    annotations:
        "helm.sh/hook": pre-delete
        "helm.sh/hook-delete-policy": hook-succeeded
        "helm.sh/hook-weight": "0"
    labels:
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    name: {{ .Release.Name }}-pre-delete-job
    namespace: kube-system
spec:
    template:
        metadata:
            labels:
                app.kubernetes.io/instance: {{ .Release.Name | quote }}
                app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
                helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
            name: "{{ .Release.Name }}"
        spec:
            containers:
                -   command: [
                        "/bin/bash",
                        "-c",
                        "/opt/scripts/append-nodehost.sh {{ .Values.clientExtensionConfig.domain }}"
                    ]
                    image: bitnami/kubectl:1.33.1
                    imagePullPolicy: IfNotPresent
                    name: "{{ .Release.Name }}-pre-delete-job"
                    volumeMounts:
                        -   mountPath: /opt/scripts
                            name: config-volume
            restartPolicy: Never
            serviceAccountName: "{{ .Release.Name }}-internal-hook-serviceaccount"
            volumes:
                -   configMap:
                        defaultMode: 0777
                        name: {{ .Release.Name }}-pre-delete-configmap
                    name: config-volume
{{- end -}}
