{{- if .Values.clientExtensionConfig.setupMainDomainOnCoreDNS -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: "{{ .Release.Name }}-internal-hook-role"
    namespace: kube-system
rules:
    -   apiGroups: [""]
        resources:
            - configmaps
        verbs:
            - get
            - patch
    -   apiGroups: ["apps"]
        resources:
            - deployments
        verbs:
            - get
            - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: "{{ .Release.Name }}-internal-hook-rolebinding"
    namespace: kube-system
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: "{{ .Release.Name }}-internal-hook-role"
subjects:
    -   kind: ServiceAccount
        name: "{{ .Release.Name }}-internal-hook-serviceaccount"
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: "{{ .Release.Name }}-internal-hook-serviceaccount"
    namespace: kube-system
{{- end -}}
