kind: ConfigMap
apiVersion: v1
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  localtest.me.server: |
    localtest.me:53 {
      errors
      template IN A localtest.me {
        match .*.localtest.me
        answer "{{ .Name }} 60 IN A __GATEWAY_IP__"
      }
      template IN AAAA localtest.me {
        match .*.localtest.me
        rcode NXDOMAIN
      }
      cache 30
      loop
      reload
      loadbalance
    }
