apiVersion: v1
kind: ConfigMap
metadata:
    annotations:
        {{- include "liferay-client-extension.ext-provision-configmap.annotations" . | nindent 8 }}
    labels:
        {{- include "liferay-client-extension.ext-provision-configmap.labels" . | nindent 8 }}
    name: {{ include "liferay-client-extension.ext-provision-configmap.name" . }}
data:
    {{- range $index, $configJson := .Values.clientExtensionConfig.configJsons }}
    {{ $.Release.Name }}-{{ $index }}.client-extension-config.json: {{ $configJson | fromJson | toPrettyJson | quote }}
    {{- end }}
