{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    {{- with .Values.ingress.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    labels:
        {{- include "liferay-client-extension.labels" . | nindent 8 }}
    name: {{ include "liferay-client-extension.fullname" . }}
spec:
    {{- with .Values.ingress.className }}
    ingressClassName: {{ . }}
    {{- end }}
    rules:
        -   host: {{ .Values.clientExtensionConfig.mainDomain | quote }}
            http:
                paths:
                    -   backend:
                            service:
                                name: {{ include "liferay-client-extension.fullname" $ }}
                                port:
                                    number: {{ $.Values.service.port }}
                        path: /
                        pathType: Prefix
        {{- range .Values.ingress.hosts }}
        -   host: {{ .host | quote }}
            http:
                paths:
                    {{- range .paths }}
                    -   backend:
                            service:
                                name: {{ include "liferay-client-extension.fullname" $ }}
                                port:
                                    number: {{ $.Values.service.port }}
                        path: {{ .path }}
                        {{- with .pathType }}
                        pathType: {{ . }}
                        {{- end }}
                    {{- end }}
        {{- end }}
    {{- if .Values.ingress.tls }}
    tls:
        {{- range .Values.ingress.tls }}
        -   hosts:
                {{- range .hosts }}
                - {{ . | quote }}
                {{- end }}
            secretName: {{ .secretName }}
        {{- end }}
    {{- end }}
{{- end }}
