{{- if .Values.serviceAccount.create -}}
apiVersion: v1
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
kind: ServiceAccount
metadata:
    {{- with .Values.serviceAccount.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    labels:
        {{- include "liferay-client-extension.labels" . | nindent 8 }}
    name: {{ include "liferay-client-extension.serviceAccountName" . }}
{{- end }}
